# -*- coding: utf-8 -*-
"""ASSIGNMENT 4 task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PUYo9vMGsCWnW3pACHTQvtfhJoqhMBdp
"""

def write_and_append_file():
    # Step 1: Take user input and write it to output.txt
    user_input = input("Enter some text to write to the file: ")
    with open("output.txt", "w") as file:
        file.write(user_input + "\n")

    # Step 2: Append additional data
    additional_input = input("Enter more text to append: ")
    with open("output.txt", "a") as file:
        file.write(additional_input + "\n")

    # Step 3: Read and display final content
    print("\nFinal content of 'output.txt':")
    with open("output.txt", "r") as file:
        for line in file:
            print(line.strip())

# Call the function
write_and_append_file()