# -*- coding: utf-8 -*-
"""ASSIGNMENT 4 task1:.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8fghR4MK8vfcXBPT_DgdjYFum9Umpda
"""

def read_file():
    try:
        with open("sample.txt", "r") as file:
            for line in file:
                print(line.strip())
    except FileNotFoundError:
        print("Error: The file 'sample.txt' does not exist.")

# Call the function
read_file()